// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: grpc/grpc.proto

package grpcpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Structmsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Rating   int32  `protobuf:"varint,3,opt,name=Rating,proto3" json:"Rating,omitempty"`
	Platform string `protobuf:"bytes,4,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Date     string `protobuf:"bytes,5,opt,name=Date,proto3" json:"Date,omitempty"`
	Err      string `protobuf:"bytes,6,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Structmsg) Reset() {
	*x = Structmsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Structmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Structmsg) ProtoMessage() {}

func (x *Structmsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Structmsg.ProtoReflect.Descriptor instead.
func (*Structmsg) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Structmsg) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Structmsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Structmsg) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Structmsg) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Structmsg) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Structmsg) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Jwtoken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Err   string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Jwtoken) Reset() {
	*x = Jwtoken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jwtoken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwtoken) ProtoMessage() {}

func (x *Jwtoken) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwtoken.ProtoReflect.Descriptor instead.
func (*Jwtoken) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Jwtoken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Jwtoken) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Userstruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Err      string `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Userstruct) Reset() {
	*x = Userstruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userstruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userstruct) ProtoMessage() {}

func (x *Userstruct) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userstruct.ProtoReflect.Descriptor instead.
func (*Userstruct) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Userstruct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Userstruct) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Userstruct) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Errmsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Errmsg) Reset() {
	*x = Errmsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Errmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Errmsg) ProtoMessage() {}

func (x *Errmsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Errmsg.ProtoReflect.Descriptor instead.
func (*Errmsg) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *Errmsg) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *Id) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_grpc_grpc_proto protoreflect.FileDescriptor

var file_grpc_grpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x22, 0x89, 0x01, 0x0a, 0x09, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x31, 0x0a, 0x07, 0x6a, 0x77, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x4e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x1a, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x22, 0x14, 0x0a, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x32, 0x81, 0x03, 0x0a, 0x04, 0x43,
	0x52, 0x55, 0x44, 0x12, 0x2d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6d, 0x73, 0x67,
	0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x22, 0x00, 0x12, 0x26, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0a, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x69, 0x64, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x62, 0x2e, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x6d, 0x73, 0x67, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62,
	0x2e, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x04, 0x52, 0x65, 0x61,
	0x64, 0x12, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x69, 0x64, 0x1a, 0x11, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6d, 0x73, 0x67,
	0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x65, 0x72,
	0x72, 0x6d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x62, 0x2e, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x1a, 0x0e, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x2e,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x1a, 0x0f, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x70, 0x62, 0x2e, 0x6a, 0x77, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00, 0x42, 0x3c,
	0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67,
	0x6f, 0x2f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_grpc_proto_rawDescOnce sync.Once
	file_grpc_grpc_proto_rawDescData = file_grpc_grpc_proto_rawDesc
)

func file_grpc_grpc_proto_rawDescGZIP() []byte {
	file_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_grpc_proto_rawDescData)
	})
	return file_grpc_grpc_proto_rawDescData
}

var (
	file_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
	file_grpc_grpc_proto_goTypes  = []interface{}{
		(*Structmsg)(nil),  // 0: grpcpb.structmsg
		(*Jwtoken)(nil),    // 1: grpcpb.jwtoken
		(*Userstruct)(nil), // 2: grpcpb.userstruct
		(*Errmsg)(nil),     // 3: grpcpb.errmsg
		(*Id)(nil),         // 4: grpcpb.id
	}
)

var file_grpc_grpc_proto_depIdxs = []int32{
	0, // 0: grpcpb.CRUD.Create:input_type -> grpcpb.structmsg
	4, // 1: grpcpb.CRUD.Delete:input_type -> grpcpb.id
	0, // 2: grpcpb.CRUD.Update:input_type -> grpcpb.structmsg
	4, // 3: grpcpb.CRUD.Read:input_type -> grpcpb.id
	2, // 4: grpcpb.CRUD.CreateUser:input_type -> grpcpb.userstruct
	2, // 5: grpcpb.CRUD.DeleteUser:input_type -> grpcpb.userstruct
	2, // 6: grpcpb.CRUD.UpdateUser:input_type -> grpcpb.userstruct
	2, // 7: grpcpb.CRUD.Login:input_type -> grpcpb.userstruct
	3, // 8: grpcpb.CRUD.Create:output_type -> grpcpb.errmsg
	3, // 9: grpcpb.CRUD.Delete:output_type -> grpcpb.errmsg
	3, // 10: grpcpb.CRUD.Update:output_type -> grpcpb.errmsg
	0, // 11: grpcpb.CRUD.Read:output_type -> grpcpb.structmsg
	3, // 12: grpcpb.CRUD.CreateUser:output_type -> grpcpb.errmsg
	3, // 13: grpcpb.CRUD.DeleteUser:output_type -> grpcpb.errmsg
	3, // 14: grpcpb.CRUD.UpdateUser:output_type -> grpcpb.errmsg
	1, // 15: grpcpb.CRUD.Login:output_type -> grpcpb.jwtoken
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_grpc_proto_init() }
func file_grpc_grpc_proto_init() {
	if File_grpc_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Structmsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jwtoken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userstruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Errmsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_grpc_proto_depIdxs,
		MessageInfos:      file_grpc_grpc_proto_msgTypes,
	}.Build()
	File_grpc_grpc_proto = out.File
	file_grpc_grpc_proto_rawDesc = nil
	file_grpc_grpc_proto_goTypes = nil
	file_grpc_grpc_proto_depIdxs = nil
}
